server.port=9091
spring.application.name=notification
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

hystrix.command.doSomethingKey.circuitBreaker.requestVolumeThreshold=2
hystrix.command.doSomethingKey.metrics.rollingStats.timeInMilliseconds=500
hystrix.command.default.circuitBreaker.errorThresholdPercentage=1
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds=10000
